package example;

import java.util.Base64;

public class Base64Tools {
	public static void main(String[] args){
		//test();
		
		//裁剪生成的字符
		/*String enStr = "MAA0ADcAOQA4ADYAQwBGAEUANwAxAEQARgA5AEYARAAwADAANABBAEMAMgBCADEAMgA1ADUAOABBAEYARABCADgANwA4ADUAQQAxADcAMwA5AEYAMgBBADMAMgBEADEARgBEADUAMQBEAEQAMwBDAEIAOQAyAEIAQwBGAEEANQBFADgAQQBDADMAMwBBAEMAOQBGADgANwAzAEQAOABBAEIAQQA2ADQARgAzAEEAOQA5AEQARQAzADIAOQA5ADkANgBGADkAQgA5ADgARgBDADMARAA5ADEAQQAyAEQAOAAzADQARgAxADIAOABGADQAOQBDADQANwA3ADEAOQA0ADQANAAwAEEANQBCAEYAOABGAEEARQBCADkANQBEADQAOAA0ADMAMgAxADkAOAA5AEQARQBGADcARgA5AEQAOQBDAEIANABEAEMAMQBCADMARgAxADcAMQBCADQARQAwAEUAMQBFAEEAMwA5ADkARAAyADYAMABDADMARQBGADgAOABDAEUARABDADAARAA3ADAARgA0ADUANgBFADgARABGAEYANQBBADQAMQBFADAANgBDADQAQwBEADIAOAA0ADAANwBBADUAQwBDADAARQA2ADYAOQBCADkARgBFADQANgA4ADMAMABEAEIANQA5AEMAMAAwADAAQgBBADYAOAAyAEQANwAxAEMANQA1AEUAOQA3AEYANABDADcAMwAxADIAQgA0ADcAQwAzADkAOQAzAEMANwBDADYAMwBDADYARQBEAEIAMAAzADYANQBDADEAOQBFADYAQwA4AEQANQAxADgAOAAxADIAMwBEADcAMwA0ADYARABCAEYAOQBFAEQARgA5ADQAMABCAEUAMAA1AEMAMQA2ADAAQQA1AEMANwA3ADcARQAwADIAQQBDADAAMgAxAEUAMgA5AEUARAAyADkARAAzAEMAMwA0AEQAQwAwADcARAA4ADgAOAA3ADEAMgA1AEQAQgBDADUAOQA4AEYAQwBFAEIAQwAxADkARgAwADgANwBCADAANQBCAEEARQA2AEYARgA4ADIARAAwAEIANgA0ADcANAA2AEIAQgBGADQANQA2ADMARABBADQAMABCADUANAAxAEIANgBDAEUANQAzAEIANgBDADYAMQAxADcANAA3ADAARQBEAEQARQBDAEEAOABEADQARQAyADUARAA3ADgAOQAzAEUARAA0ADMAMAA4AEEAMwA1AEEANQBDADAARQA2ADQAQwAxADEAOAAyAEUANABDADQAMgBEADIANAA4ADEARABEADkANAA5ADIAQQBGADYAQQA1ADAARABCADMAQQA5ADkAQQA5ADgANQAyADEANAA3AA==";
		String cutData = cutData(enStr);
		System.out.println("cutDate = " + cutData);*/
	}
	
	public static void test(){
		byte[] des = new byte[512];
		String enStr = "MAA0ADcAOQA4ADYAQwBGAEUANwAxAEQARgA5AEYARAAwADAANABBAEMAMgBCADEAMgA1ADUAOABBAEYARABCADgANwA4ADUAQQAxADcAMwA5AEYAMgBBADMAMgBEADEARgBEADUAMQBEAEQAMwBDAEIAOQAyAEIAQwBGAEEANQBFADgAQQBDADMAMwBBAEMAOQBGADgANwAzAEQAOABBAEIAQQA2ADQARgAzAEEAOQA5AEQARQAzADIAOQA5ADkANgBGADkAQgA5ADgARgBDADMARAA5ADEAQQAyAEQAOAAzADQARgAxADIAOABGADQAOQBDADQANwA3ADEAOQA0ADQANAAwAEEANQBCAEYAOABGAEEARQBCADkANQBEADQAOAA0ADMAMgAxADkAOAA5AEQARQBGADcARgA5AEQAOQBDAEIANABEAEMAMQBCADMARgAxADcAMQBCADQARQAwAEUAMQBFAEEAMwA5ADkARAAyADYAMABDADMARQBGADgAOABDAEUARABDADAARAA3ADAARgA0ADUANgBFADgARABGAEYANQBBADQAMQBFADAANgBDADQAQwBEADIAOAA0ADAANwBBADUAQwBDADAARQA2ADYAOQBCADkARgBFADQANgA4ADMAMABEAEIANQA5AEMAMAAwADAAQgBBADYAOAAyAEQANwAxAEMANQA1AEUAOQA3AEYANABDADcAMwAxADIAQgA0ADcAQwAzADkAOQAzAEMANwBDADYAMwBDADYARQBEAEIAMAAzADYANQBDADEAOQBFADYAQwA4AEQANQAxADgAOAAxADIAMwBEADcAMwA0ADYARABCAEYAOQBFAEQARgA5ADQAMABCAEUAMAA1AEMAMQA2ADAAQQA1AEMANwA3ADcARQAwADIAQQBDADAAMgAxAEUAMgA5AEUARAAyADkARAAzAEMAMwA0AEQAQwAwADcARAA4ADgAOAA3ADEAMgA1AEQAQgBDADUAOQA4AEYAQwBFAEIAQwAxADkARgAwADgANwBCADAANQBCAEEARQA2AEYARgA4ADIARAAwAEIANgA0ADcANAA2AEIAQgBGADQANQA2ADMARABBADQAMABCADUANAAxAEIANgBDAEUANQAzAEIANgBDADYAMQAxADcANAA3ADAARQBEAEQARQBDAEEAOABEADQARQAyADUARAA3ADgAOQAzAEUARAA0ADMAMAA4AEEAMwA1AEEANQBDADAARQA2ADQAQwAxADEAOAAyAEUANABDADQAMgBEADIANAA4ADEARABEADkANAA5ADIAQQBGADYAQQA1ADAARABCADMAQQA5ADkAQQA5ADgANQAyADEANAA3AA==";
		//String enStr = "ABGOc/ancTzUGgoQBbRWVwGYGT6KFW0ERVyeJHulbG8mPI+dqw9d8iHAEMHYAY3vMhN6hDMP7uprnsEbrCcUgguqAym1/x37M47pyY7Mbb5Kpsm4RKNezKu4+TAM/6B4ReZSpA0gMAo8eZFGTOi22H3Jw+V5vmO8B0QV99X/sSI=";
		byte[] decode = Base64.getDecoder().decode(enStr);
		System.out.println("decode  =  " + new String(decode));
		byte b = decode[1];
		int times = 0;
		for(int i = 0, j = 0; i < decode.length; i++){
			if(b == decode[i]){
				//System.out.println("相同元素");
				times++;
				continue;
			}
			des[j++] = decode[i];
		}
		System.out.println("times = " + times);
		System.out.println("des = " + new String(des));
		
	}
	
	public static String cutData(String enStr){
		byte[] des = new byte[512];
		byte[] decode = Base64.getDecoder().decode(enStr);
		System.out.println("decode  =  " + new String(decode));
		byte b = decode[1];
		int times = 0;
		for(int i = 0, j = 0; i < decode.length; i++){
			if(b == decode[i]){
				times++;
				continue;
			}
			des[j++] = decode[i];
		}
		
		return new String(des);
	}
}
